SELECT (
    SELECT DISTINCT SALARY
    FROM (
        SELECT SALARY, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RNK
        FROM EMPLOYEE
    ) AS SALARIES
    WHERE RNK = 2
) AS SECONDHIGHESTSALARY;
