SELECT S.NAME
FROM SALESPERSON S
WHERE S.NAME NOT IN (
    SELECT S.NAME
    FROM SALESPERSON S
    LEFT JOIN ORDERS O ON O.SALES_ID = S.SALES_ID
    LEFT JOIN COMPANY C ON O.COM_ID = C.COM_ID
    WHERE C.NAME = 'RED'
)