SELECT D1.NAME AS DEPARTMENT,E1.NAME AS EMPLOYEE, E1.SALARY AS SALARY
FROM EMPLOYEE E1 JOIN DEPARTMENT D1
ON E1.DEPARTMENTID = D1.ID
WHERE (
    SELECT COUNT(DISTINCT E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPARTMENTID = E1.DEPARTMENTID AND E2.SALARY > E1.SALARY
) IN (0,1,2);